# Generated by Django 6.1.1 on 2026-09-21 07:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Sinf nomi (masalan: 1-A)')),
                ('grade_level', models.PositiveSmallIntegerField(default=1, verbose_name='Sinf bosqichi (1-11)')),
                ('academic_year', models.CharField(default='2025-2026', max_length=20, verbose_name="O'quv yili")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol holatda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Sinf',
                'verbose_name_plural': 'Sinflar',
                'ordering': ['grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='Telefon raqami')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP kodi')),
                ('is_used', models.BooleanField(default=False, verbose_name='Ishlatilgan')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Urinishlar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Telefon OTP kodi',
                'verbose_name_plural': 'Telefon OTP kodlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Fan nomi')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='Fan kodi')),
                ('icon', models.CharField(default='book-open', max_length=50, verbose_name='Lucide icon nomi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol holatda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('role', models.CharField(default="O'qituvchi / Administrator", max_length=100, verbose_name='Lavozimi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrator profili',
                'verbose_name_plural': 'Administrator profillari',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Vazifa nomi')),
                ('description', models.TextField(blank=True, verbose_name='Vazifa tavsifi')),
                ('content', models.TextField(blank=True, verbose_name="Vazifa to'liq matni")),
                ('attachment', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Asosiy fayl (ixtiyoriy)')),
                ('video_url', models.URLField(blank=True, verbose_name='Video havola (YouTube / video link)')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Berilgan sana')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Boshlanish vaqti')),
                ('due_date', models.DateTimeField(verbose_name='Topshirish muddati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name="Yaratgan o'qituvchi")),
                ('classrooms', models.ManyToManyField(related_name='assignments', to='core.classroom', verbose_name='Biriktirilgan sinflar')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Uy vazifasi',
                'verbose_name_plural': 'Uy vazifalari',
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='assignments/attachments/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(default='document', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Amal')),
                ('target_model', models.CharField(blank=True, max_length=100, verbose_name='Obyekt modeli')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='Obyekt ID')),
                ('details', models.TextField(blank=True, verbose_name="Batafsil ma'lumot")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Audit jurnali',
                'verbose_name_plural': 'Audit jurnallari',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiyasi')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol holatda')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan sana")),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classroom', verbose_name='Sinfi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'quvchi profili",
                'verbose_name_plural': "O'quvchilar profillari",
                'ordering': ['classroom__grade_level', 'classroom__name', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Bajarilmagan'), ('completed', 'Bajarildi'), ('submitted', 'Javob yuborildi'), ('under_review', 'Tekshirilmoqda'), ('approved', 'Qabul qilindi'), ('needs_work', 'Qayta ishlash kerak'), ('overdue', 'Muddati o‘tgan')], default='not_started', max_length=30, verbose_name='Holat')),
                ('marked_done_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan vaqt')),
                ('completed_without_files', models.BooleanField(default=False, verbose_name='Faylsiz bajarildi deb belgilangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='core.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='core.studentprofile')),
            ],
            options={
                'verbose_name': "O'quvchi topshirig'i",
                'verbose_name_plural': "O'quvchilar topshiriqlari",
                'ordering': ['-assignment__due_date'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.CreateModel(
            name='ProfileChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_first_name', models.CharField(blank=True, max_length=100, verbose_name='Yangi ism')),
                ('requested_last_name', models.CharField(blank=True, max_length=100, verbose_name='Yangi familiya')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.classroom', verbose_name='Yangi sinf')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='core.studentprofile')),
            ],
            options={
                'verbose_name': "Profil o'zgartirish so'rovi",
                'verbose_name_plural': "Profil o'zgartirish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True, verbose_name="O'quvchi matnli javobi")),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana va vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan vaqt")),
                ('review_status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('under_review', 'Tekshirilmoqda'), ('approved', 'Qabul qilindi'), ('needs_work', 'Qayta ishlash kerak')], default='pending', max_length=30, verbose_name="O'qituvchi xulosasi")),
                ('teacher_feedback', models.TextField(blank=True, verbose_name="O'qituvchi izohi")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tekshirilgan sana')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name="Tekshirgan o'qituvchi")),
                ('student_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='core.studentassignment')),
            ],
            options={
                'verbose_name': 'Yuborilgan topshiriq javobi',
                'verbose_name_plural': 'Yuborilgan topshiriq javoblari',
            },
        ),
        migrations.CreateModel(
            name='SubmissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/files/')),
                ('file_type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video'), ('document', 'Hujjat (PDF/Word)'), ('other', 'Boshqa')], default='image', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(default=0, help_text='Baytlarda')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.submission')),
            ],
            options={
                'verbose_name': 'Topshiriq fayli',
                'verbose_name_plural': 'Topshiriq fayllari',
            },
        ),
        migrations.CreateModel(
            name='SubmissionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Harakat nomi')),
                ('old_status', models.CharField(blank=True, max_length=50)),
                ('new_status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqti')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="O'zgartiruvchi")),
                ('student_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.studentassignment')),
            ],
            options={
                'verbose_name': 'Topshiriq tarixi',
                'verbose_name_plural': 'Topshiriqlar tarixi',
                'ordering': ['-timestamp'],
            },
        ),
    ]
