# Generated by Django 6.1.1 on 2026-09-21 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': "Administrator / O'qituvchi profili", 'verbose_name_plural': "Administrator va O'qituvchilar profillari"},
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='classrooms',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='core.classroom', verbose_name='Biriktirilgan sinflar'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='raw_password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Admin bergan parol'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.subject', verbose_name='Biriktirilgan fan'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='raw_password',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Biriktirilgan parol'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Bosh administrator'), ('teacher', "O'qituvchi")], default='teacher', max_length=30, verbose_name='Roli'),
        ),
    ]
